blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "blog" # Creating a namespace so I can use the url building stuff
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path("markdownx/", include("markdownx.urls")),
    path("", include("blog.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django import forms
import datetime
from django.utils import timezone
from markdownx.models import MarkdownxField

class Post(models.Model):
    post_title = models.CharField(max_length=100)
    post_text = models.CharField(max_length=200000)
    post_text_field = models.TextField(max_length=200000)
    pub_date = models.DateTimeField("date published")
    post_style = models.CharField(max_length=6)
    post_summary = models.CharField(max_length=20)
    post_title = models.CharField(max_length=255)
    post_text_field = MarkdownxField()
    
    def __str__(self):
        return self.post_title
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
class PostImage(models.Model):
    post = models.ForeignKey(Post, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post_images/')

blog/views.py
from django.shortcuts import render,get_object_or_404
import markdown # For ToC
# Create your views here.
from django.http import HttpResponse
from .models import Post
from django.template import loader
from django.http import Http404
from django.views import generic

md_extensions = ['extra', 'toc']

class IndexView(generic.ListView):
    context_object_name = "latest_post_list"
    # latest_post_list = Post.objects.order_by("-pub_date")[:5]
    template_name = "blog/index.html"
    # context = {"latest_post_list": latest_post_list}
    
    def get_queryset(self): 
        return Post.objects.order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
    model = Post
    template_name = "blog/post.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Render Markdown with ToC
        post_body = self.object.post_text_field
        md = markdown.Markdown(extensions=['extra', 'toc'])
        post_html = md.convert(post_body)
        toc_html = md.toc

        # Add both to context
        context['post_html'] = post_html
        context['toc_html'] = toc_html
        return context

blog/templates/blog/footer.html
{% load static %}					
<footer id="footer">
						<div class="inner">
							<section>
								<h2>Follow</h2>
								<ul class="icons">
									<li><a href="https://github.com/DewewRHINO" class="icon brands style2 fa-github"><span class="label">GitHub</span></a></li>
									<li><a href="https://www.linkedin.com/in/jacobjayme/" class="icon brands style2 fa-linkedin"><span class="label">Linkedin</span></a></li>
									<li><a href="mailto:jaymerjacob@gmail.com" class="icon solid style2 fa-envelope"><span class="label">Email</span></a></li>
								</ul>
							</section>
							<ul class="copyright">
								<li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>
						</div>
					</footer>
			</div>

		<!-- Scripts -->
			<script src="{% static 'blog/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'blog/assets/js/browser.min.js' %}"></script>
			<script src="{% static 'blog/assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'blog/assets/js/util.js' %}"></script>
			<script src="{% static 'blog/assets/js/main.js' %}"></script>

blog/templates/blog/header.html
{% load static %}

<head>
	<title>jacobjayme.xyz</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<link rel="stylesheet" href="{% static 'blog/assets/css/main.css' %}"/>
	<noscript><link rel="stylesheet" href="{% static 'blog/assets/css/noscript.css' %}" /></noscript>
</head>

blog/templates/blog/index.html
{% load static %}

<!DOCTYPE HTML>
<!--
	Phantom by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
{% include "./header.html" %}

<body class="is-preload">
	<div id="wrapper">
		{% include "./navbar.html" %}

		{% include "./menu.html" %}

		<div id="main">
			<div class="inner">
				<header>
					<h1>Welcome to jacobjayme.xyz!</h1>
						<p>
							<a href="" class="typewrite" data-period="2000" data-type='[ "CS @ Cal Poopy", "Security Engineer @ Cisco", "Masters in Cyber @ Georgia Tech", "I hate computers." ]'>
								<span class="wrap"></span>
							</a>
						</p>
					<p>I will be sharing projects, experiences, and write-ups on this website.</p>
				</header>
				<section class="tiles">
					{% if latest_post_list %}
					{% for post in latest_post_list %}
					<article class="{{post.post_style}}">
						<span class="image">
							<img src="{% static 'blog/images/pic01.jpg' %}" alt="" />
						</span>
						<a href="{% url 'blog:detail' post.id %}">
							<h2>{{post.post_title}}</h2>
							<div class="content">
								<p>{{post.post_summary}}</p>
							</div>
						</a>
					</article>
					{% endfor %}
					{% else %}
					<p>No Blogs at the moment.</p>
					{% endif %}
				</section>
			</div>
		</div>
		{% include "./footer.html" %}
</body>

</html>

blog/templates/blog/menu.html
<nav id="menu">
  <h2>Menu</h2>
  <ul>
    <li><a href="/">Home</a></li>
  </ul>
</nav>

blog/templates/blog/navbar.html
{% load static %}
<header id="header">
  <div class="inner">
    <a href="/" class="logo">
      <span class="symbol"
        ><img src="{% static 'blog/images/logo.svg' %}" alt="" /></span
      ><span class="title">jacobjayme.xyz</span>
    </a>
    <nav>
      <ul>
        <li><a href="#menu">Menu</a></li>
      </ul>
    </nav>
  </div>
</header>

blog/templates/blog/post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% include "./header.html" %}
  <link rel="stylesheet" href="{% static 'blog/assets/css/toc.css' %}">
  <body class="is-preload">
    <div id="wrapper">
      {% include "./navbar.html" %}
      {% include "./menu.html" %}

      <!-- Main content area with ToC and Post -->
      <div class="content-wrapper">
        
        <!-- Sticky Table of Contents -->
        <aside class="toc-container">
          <h3>On this page</h3>
          <nav id="toc">
            {{ toc_html|safe }}
          </nav>
        </aside>

        <!-- Main Blog Content -->
        <main id="main">
          <div class="inner">
            <section>
              <h1>{{ post.post_title }}</h1>
              {% if post.featured_image %}
                <span class="image main">
                  <img src="{{ post.featured_image.url }}" alt="{{ post.post_title }}" />
                </span>
              {% endif %}
              {{ post_html|safe }}
            </section>
          </div>
        </main>

      </div>

      {% include "./footer.html" %}
    </div>
  </body>
</html>